# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='capactiy',
            new_name='capacity',
        ),
    ]
