# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagyr',
            name='opponent_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='opponent_id_wagyr', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='wagyr',
            name='wagyr_winner',
            field=models.ForeignKey(blank=True, choices=[(1, models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='self_id_wagyr', to=settings.AUTH_USER_MODEL, to_field='username')), (2, models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='opponent_id_wagyr', to=settings.AUTH_USER_MODEL, to_field='username'))], null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
