# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160406_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='venue',
            field=models.OneToOneField(blank=True, db_column='venue', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_venue', to='app.Venue'),
        ),
    ]
