# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160406_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'managed': True, 'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='venue',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='zip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
